name: workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: 'World'
jobs:
  printLog:
    runs-on: ubuntu-latest

    steps:
    - name: print log
      run: echo "Hello! ${{ github.event.inputs.name }}"